# Create user.

POST http://localhost:5000/api/users/sign-up HTTP/1.1
Content-Type: application/json

{
  "name": "Андрей",
  "email": "vokshin@ya.ru",
  "password": "123456",
  "role": "admin"
}

###
# Login user.

POST http://localhost:5000/api/users/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "vokshin@ya.ru",
  "password": "123456"
}

###
# Get user by user ID.

GET http://localhost:5000/api/users/abc0c2b2-f617-40df-a542-75c54a245668 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMwYzJiMi1mNjE3LTQwZGYtYTU0Mi03NWM1NGEyNDU2NjgiLCJlbWFpbCI6InZva3NoaW5AeWEucnUiLCJpYXQiOjE3NTIyNjQxNjEsImV4cCI6MTc1MjI3NDk2MX0.vN7_-gxsWo--dWG1aCLmJvTlc4tN8YxXZ_9SCJCURsM
Content-Type: application/json

###
# Refresh token.

POST http://localhost:5000/api/users/refresh-token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMwYzJiMi1mNjE3LTQwZGYtYTU0Mi03NWM1NGEyNDU2NjgiLCJlbWFpbCI6InZva3NoaW5AeWEucnUiLCJ0b2tlbklkIjoiNDMxMzNiMGMtNTExYy00N2ViLTlmNDMtNGViNTQzNWE5OWI5IiwiaWF0IjoxNzUyMjY0MTYxLCJleHAiOjE3NTI4Njg5NjF9.2Gsyhk9czD1bZY_9vS5j2kHaGxKFR9_mg3eXXY6rvEU
Content-Type: application/json

###
# Check token.

POST http://localhost:5000/api/users/check-token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMwYzJiMi1mNjE3LTQwZGYtYTU0Mi03NWM1NGEyNDU2NjgiLCJlbWFpbCI6InZva3NoaW5AeWEucnUiLCJpYXQiOjE3NTIyNjQxNjEsImV4cCI6MTc1MjI3NDk2MX0.vN7_-gxsWo--dWG1aCLmJvTlc4tN8YxXZ_9SCJCURsM
Content-Type: application/json

###
# Create product.

POST http://localhost:5000/api/products/add HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTRlZGEwYi1kZTc1LTRlNzUtYWIyZC1iMzhhZDRkYjE5ZjMiLCJlbWFpbCI6InZva3NoaW5AeWEucnUiLCJpYXQiOjE3NTI1MTk3NDgsImV4cCI6MTc1MjUzMDU0OH0.gSbuys9SAWft54i-i_rGGesoji780b7FHyw2ih3N9nM
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="catalog-product-0.png"
Content-Type: image/png

< C:\Users\strim\Desktop\1770169-guitar\apps\frontend\public\img\content\catalog-product-8.png
--MyBoundary
Content-Disposition: form-data; name="title"

Гитара Fender Telecaster
--MyBoundary
Content-Disposition: form-data; name="article"

FEN505
--MyBoundary
Content-Disposition: form-data; name="type"

electro
--MyBoundary
Content-Disposition: form-data; name="description"

Электрогитара Fender Telecaster с ярким звуком и классическим дизайном. Идеальна для кантри и рок-музыки.
--MyBoundary
Content-Disposition: form-data; name="price"

15000
--MyBoundary
Content-Disposition: form-data; name="stringCount"

seven
--MyBoundary
Content-Disposition: form-data; name="date"

2025-04-05T16:16:47.285Z
--MyBoundary--

###
# Update product.

PATCH http://localhost:5000/api/products/123e4567-e89b-12d3-a456-426614174000/edit HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMwYzJiMi1mNjE3LTQwZGYtYTU0Mi03NWM1NGEyNDU2NjgiLCJlbWFpbCI6InZva3NoaW5AeWEucnUiLCJpYXQiOjE3NTIyNjQxNjEsImV4cCI6MTc1MjI3NDk2MX0.vN7_-gxsWo--dWG1aCLmJvTlc4tN8YxXZ_9SCJCURsM
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="catalog-product-0.png"
Content-Type: image/png

< C:\Users\strim\Desktop\1770169-guitar\apps\frontend\public\img\content\catalog-product-0.png
--MyBoundary
--MyBoundary
Content-Disposition: form-data; name="type"

electro
--MyBoundary--

###
# Get product by product ID.

GET http://localhost:5000/api/products/014f97df-758e-4308-a8b8-d7f9c7e7238d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMwYzJiMi1mNjE3LTQwZGYtYTU0Mi03NWM1NGEyNDU2NjgiLCJlbWFpbCI6InZva3NoaW5AeWEucnUiLCJpYXQiOjE3NTIyODgwMjcsImV4cCI6MTc1MjI5ODgyN30.7S177-nOxi33B5I7Jy5XNFaSK54USdeod9RlM5pWfrU
Content-Type: application/json

###
# Get products.

GET http://localhost:5000/api/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTRlZGEwYi1kZTc1LTRlNzUtYWIyZC1iMzhhZDRkYjE5ZjMiLCJlbWFpbCI6InZva3NoaW5AeWEucnUiLCJpYXQiOjE3NTIyOTExMzAsImV4cCI6MTc1MjMwMTkzMH0.R7foZGATd9DOVXPO9yrVkwjlwI4SB1vEQ_VTlddXivA

Content-Type: application/json

###
# Get products with query.

GET http://localhost:5000/api/products?types[]=electro&types[]=ukulele&price=desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTRlZGEwYi1kZTc1LTRlNzUtYWIyZC1iMzhhZDRkYjE5ZjMiLCJlbWFpbCI6InZva3NoaW5AeWEucnUiLCJpYXQiOjE3NTIyOTExMzAsImV4cCI6MTc1MjMwMTkzMH0.R7foZGATd9DOVXPO9yrVkwjlwI4SB1vEQ_VTlddXivA
Content-Type: application/json

###
# Delete product by product id.

DELETE  http://localhost:5000/api/products/014f97df-758e-4308-a8b8-d7f9c7e7238d/delete HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTRlZGEwYi1kZTc1LTRlNzUtYWIyZC1iMzhhZDRkYjE5ZjMiLCJlbWFpbCI6InZva3NoaW5AeWEucnUiLCJpYXQiOjE3NTIyOTExMzAsImV4cCI6MTc1MjMwMTkzMH0.R7foZGATd9DOVXPO9yrVkwjlwI4SB1vEQ_VTlddXivA
Content-Type: application/json

###
